### ISSUE TITLE
Silently re-fetching auth token fails

### ISSUE THREAD

**Issue by DominicLuidold** [vacatius/mobile-app#40]
**Describe the bug**
Silently re-fetching a new auth token fails if one is inactive for a couple of minutes. Rather than being able to continue with the desired action, an error occurs and the user has to perform the action twice.

**To Reproduce**
1. Open the app, be inactive for a couple of minutes
2. Click on a button/etc. that performs a backend request
3. See error

**Expected behavior**
The auth token should get re-fetched silently without throwing an error along a stack trace.

**Screenshots**
![image](https://user-images.githubusercontent.com/22751730/115716687-b6e89c00-a379-11eb-8c22-7e9e3996629d.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS 14.4.2
 - Version: latest from develop

**Additional context**
None

**Comment by alexw-at** [comment]
The problem is caused by cookies. Maybe the refresh token could be moved to the LoginResult and then used as input for the refreshToken mutation? @valentingc

**Comment by valentingc** [comment]
@alexw-at Yeah that's possible, however, this then only works for mobile devices that have a secure storage. Regular websites have no way of securely storing the token (LocalStorage is readable by JS) so that's why I have used a secure cookie - those are only transmitted to the same origin, only in HTTPs environments and they are not readable by JS. But I can change it, however, we have to keep in mind that once we want to add a website too that we then have shifted the problem there.
Sooner or later it'll maybe be a good idea to use some authentication provider such as Auth0 or Okta so that they can take care of that.

**Comment by valentingc** [comment]
@alexw-at Could you deploy the app (using the expo CLI) to your Android phone to check if it only affects development time with Expo reloads? Then we'd know if it is "just" expo.

**Comment by alexw-at** [comment]
The installed app doesn't work either. I still get the no token in cookie error message.
